# Generated by Django 4.0.4 on 2022-04-16 08:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('clock_in', models.DateTimeField(auto_now=True)),
                ('ssn', models.IntegerField()),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('office', models.TextField()),
                ('specialty', models.CharField(max_length=30)),
                ('file_number', models.IntegerField()),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
